version: '3'

services:
  api:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - API_BASE_URL=http://localhost:8080
      - APP_BASE_URL=http://localhost:3000
    env_file:
      - .env
